print ("Conversacion:")
print (f"¿como te llamas?")
nombre =input ("")
print (f"Encantado {nombre}")
comunidad = input ("¿En que pueblo vives?")
print (f"Que bien, yo vivo tambien en {comunidad}")
print (f"Oye, y en que zona de {comunidad}?")
pueblo = input ("Aqui en ")
print (f"Pues yo justo al lado de {pueblo}")
print (f"Y sabes el codpostal?")
codpostal = input ("")
print (f"Pues no se si es {codpostal} o me equivoco")
print (f"Dime la calle porfavor")
calle = input ("")
print (f"Anda si eres vecino mio {nombre}, justo yo vivia en {comunidad}, y mi amigo de {comunidad} vivia por {calle} pero no me acuerdo si el cp era el {codpostal}")